version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: foliohub_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
  server:
    container_name: foliohub_server
    restart: always
    build: .
    ports:
      - '3001:3001'
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - db
